services:
  - type: web
    name: schedule-management-system
    env: node
    plan: free
    region: oregon
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /